### ISSUE TITLE
[Gallery] Image thumbnail size

### ISSUE THREAD

**Issue by salamca** [plezanje-net/next-web#28]
Some images are very small. Sometimes they are smaller than the ideal size of the thumbnail. In such case they sould stay sized to their intrinsic size; they should not be enlarged.

**Comment by demshy** [comment]
try `gallery-slider` branch an see if you can find any.. looks ok to me here: http://localhost:3003/plezalisce/bohinjska-bela/galerija

**Comment by salamca** [comment]
resolved with https://github.com/plezanje-net/next-web/pull/27
